#' @title Simulate a holobiont redox dataset with spatio-temporal structure
#'
#' @description
#' Generates a synthetic plant-soil-microbiome dataset with latent redox
#' dynamics, hydrological disturbance, plant physiological responses, radial
#' oxygen loss, root exudation, soil redox chemistry, dissolved organic carbon,
#' water content, redox-buffering proxies, microbial abundance, microbial
#' redox functional traits, gene coverage, and optional MetaT gene
#' expression or upregulation features.
#'
#' @details
#' The simulator is designed for demonstrations, benchmarking, package examples,
#' and method development. It represents a simplified soil-plant-microbiome
#' continuum in which hydrological forcing modifies latent redox state, soil
#' water content, electron-donor supply, electron-acceptor availability, plant
#' stress, radial oxygen loss, rhizodeposition, microbial abundance, redox
#' process potential, and functional gene response.
#'
#' The microbial functional layer includes synthetic proxies for aerobic
#' respiration, nitrate reduction, Fe/Mn/humic extracellular electron transfer,
#' sulfate reduction, methanogenesis, redox mediator production, ROS
#' detoxification, AMF connectivity, protistan grazing, viral lysis, microbial
#' memory, and redox flexibility.
#'
#' The generated data are synthetic and are not intended to represent any real
#' ecosystem. Parameter values are chosen to generate biologically interpretable
#' covariance structure rather than calibrated field realism.
#' #' Users are not required to measure every variable generated by the simulator.
#' The simulator returns a rich synthetic benchmark dataset, but external
#' datasets may contain fewer variables. Downstream RedoxRRI functions require
#' only row-aligned data frames for the domains used in the analysis. For
#' example, `rri_pipeline_st()` can be run with a small set of plant,
#' soil, and microbial variables, and `rri_recovery_metrics()` can be run
#' directly on any precomputed RRI trajectory stored in `res$row_scores`.
#'
#' @param n_plot Integer >= 1. Number of plots.
#' @param n_depth Integer >= 1. Number of soil depth strata.
#' @param n_plant Integer >= 1. Number of plants per plot-depth combination.
#' @param n_time Integer >= 2. Number of time points per plant.
#' @param p_micro Integer >= 1. Number of microbial abundance features.
#' @param p_gene Integer >= 1. Number of microbial functional gene features.
#' @param seed Optional integer seed. Use \code{NULL} for stochastic runs.
#' @param include_graph Logical. If \code{TRUE} and \pkg{igraph} is available,
#'   returns a simulated microbial network.
#' @param depth_labels Optional character vector of length \code{n_depth}. If
#'   \code{NULL}, depths are labelled \code{"D1"}, \code{"D2"}, ...
#' @param gene_mode Character. One of \code{"both"}, \code{"abundance"},
#'   \code{"metat"}, or \code{"none"}. Controls whether synthetic functional
#'   gene coverage, MetaT expression, both, or neither are returned.
#' @param disturbance_strength Numeric in \code{[0, 1]}. Magnitude of the
#'   disturbance pulse.
#' @param disturbance_center Optional numeric. If \code{NULL}, the disturbance
#'   is centred at the median time point.
#' @param disturbance_width Numeric > 0. Pulse width as a fraction of the season
#'   length.
#' @param seasonal_amp Numeric >= 0. Amplitude of seasonal forcing.
#' @param seasonal_phase Numeric. Phase shift for seasonal forcing in radians.
#' @param stochastic_reassembly Logical. If \code{TRUE}, microbial counts include
#'   a stochastic reassembly component.
#' @param decoupling Numeric in \code{[0, 1]}. Cross-domain decoupling. Higher
#'   values weaken deterministic coupling between latent redox state and
#'   observed domains.
#' @param zero_inflation Numeric in \code{[0, 1]}. Probability that a microbial
#'   abundance entry is set to zero.
#' @param MNAR_strength Numeric in \code{[0, 1]}. Strength of missing-not-at-random
#'   Eh dropout under strongly reduced states.
#' @param Eh_dropout_threshold Numeric in \code{[0, 1]}. Latent redox threshold
#'   below which Eh dropout can occur.
#' @param micro_mean Numeric > 0. Baseline mean intensity for microbial counts.
#' @param micro_slope Numeric >= 0. Coupling strength between reduced redox
#'   state and microbial abundance.
#' @param micro_lambda_min Numeric > 0. Lower bound for microbial Poisson
#'   intensity.
#' @param micro_lambda_max Numeric > 0. Upper bound for microbial Poisson
#'   intensity.
#' @param metat_noise Numeric >= 0. Noise level added to simulated
#'   metatranscriptomic expression.
#'
#' @return
#' A named list with:
#' \itemize{
#'   \item \code{id}: Experimental design data frame.
#'   \item \code{ROS_flux}: Plant physiological and rhizosphere boundary-flux
#'   variables.
#'   \item \code{Eh_stability}: Soil redox, hydrological, carbon, and
#'   electron-buffering variables.
#'   \item \code{micro_data}: Microbial abundance feature matrix.
#'   \item \code{micro_traits}: Microbial redox functional trait proxies.
#'   \item \code{gene_abundance}: Optional synthetic functional gene
#'   coverage/abundance matrix.
#'   \item \code{gene_expression}: Optional synthetic MetaT expression matrix.
#'   \item \code{gene_log2fc}: Optional synthetic MetaT log2 fold-change matrix
#'   relative to the pre-disturbance baseline.
#'   \item \code{latent_truth}: Underlying latent redox state in \code{[0, 1]}.
#'   \item \code{graph}: Optional \code{igraph} object.
#' }
#'
#' @importFrom stats median plogis rnorm rpois runif
#'
#' @examples
#' sim <- simulate_redox_holobiont(
#'   n_plot = 2,
#'   n_depth = 2,
#'   n_plant = 2,
#'   n_time = 8,
#'   p_micro = 20,
#'   p_gene = 36,
#'   gene_mode = "both",
#'   seed = 1
#' )
#'
#' names(sim$ROS_flux)
#' names(sim$Eh_stability)
#' names(sim$micro_traits)
#' names(sim$gene_abundance)
#' names(sim$gene_log2fc)
#'
#' res <- rri_pipeline_st(
#'   ROS_flux = sim$ROS_flux,
#'   Eh_stability = sim$Eh_stability,
#'   micro_data = cbind(
#'     sim$micro_data,
#'     sim$micro_traits,
#'     sim$gene_abundance,
#'     sim$gene_log2fc
#'   ),
#'   id = sim$id,
#'   reducer = "per_domain",
#'   scaling = "pnorm"
#' )
#'
#' head(res$row_scores)
#'
#' @export
simulate_redox_holobiont <- function(
    n_plot = 4,
    n_depth = 2,
    n_plant = 5,
    n_time = 15,
    p_micro = 60,
    p_gene = 36,
    seed = 123,
    include_graph = FALSE,
    depth_labels = NULL,
    gene_mode = c("both", "abundance", "metat", "none"),
    disturbance_strength = 0.4,
    disturbance_center = NULL,
    disturbance_width = 0.10,
    seasonal_amp = 0.08,
    seasonal_phase = 0,
    stochastic_reassembly = TRUE,
    decoupling = 0.3,
    zero_inflation = 0.4,
    MNAR_strength = 0.4,
    Eh_dropout_threshold = 0.25,
    micro_mean = 8,
    micro_slope = 3,
    micro_lambda_min = 1e-8,
    micro_lambda_max = 1e6,
    metat_noise = 0.25
) {
  gene_mode <- base::match.arg(gene_mode)

  clamp01 <- function(x) {
    base::pmin(base::pmax(x, 0), 1)
  }

  safe_scale01 <- function(x) {
    r <- base::range(x, na.rm = TRUE)
    if (!base::all(base::is.finite(r)) || base::diff(r) == 0) {
      return(base::rep(0.5, base::length(x)))
    }
    (x - r[1]) / base::diff(r)
  }

  assert_int1 <- function(x, nm, min_val) {
    if (!base::is.numeric(x) ||
        base::length(x) != 1 ||
        !base::is.finite(x) ||
        x != base::as.integer(x) ||
        x < min_val) {
      base::stop(nm, " must be a single integer >= ", min_val, ".",
                 call. = FALSE)
    }

    invisible(TRUE)
  }

  assert_num1 <- function(x, nm) {
    if (!base::is.numeric(x) ||
        base::length(x) != 1 ||
        !base::is.finite(x)) {
      base::stop(nm, " must be a single finite numeric value.",
                 call. = FALSE)
    }

    invisible(TRUE)
  }

  if (!base::is.null(seed)) {
    assert_num1(seed, "seed")
    base::set.seed(base::as.integer(seed))
  }

  assert_int1(n_plot, "n_plot", 1)
  assert_int1(n_depth, "n_depth", 1)
  assert_int1(n_plant, "n_plant", 1)
  assert_int1(n_time, "n_time", 2)
  assert_int1(p_micro, "p_micro", 1)
  assert_int1(p_gene, "p_gene", 1)

  assert_num1(disturbance_strength, "disturbance_strength")
  assert_num1(disturbance_width, "disturbance_width")
  assert_num1(seasonal_amp, "seasonal_amp")
  assert_num1(seasonal_phase, "seasonal_phase")
  assert_num1(decoupling, "decoupling")
  assert_num1(zero_inflation, "zero_inflation")
  assert_num1(MNAR_strength, "MNAR_strength")
  assert_num1(Eh_dropout_threshold, "Eh_dropout_threshold")
  assert_num1(micro_mean, "micro_mean")
  assert_num1(micro_slope, "micro_slope")
  assert_num1(micro_lambda_min, "micro_lambda_min")
  assert_num1(micro_lambda_max, "micro_lambda_max")
  assert_num1(metat_noise, "metat_noise")

  disturbance_strength <- clamp01(disturbance_strength)
  decoupling <- clamp01(decoupling)
  zero_inflation <- clamp01(zero_inflation)
  MNAR_strength <- clamp01(MNAR_strength)
  Eh_dropout_threshold <- clamp01(Eh_dropout_threshold)

  if (disturbance_width <= 0) {
    base::stop("`disturbance_width` must be > 0.", call. = FALSE)
  }

  if (seasonal_amp < 0) {
    base::stop("`seasonal_amp` must be >= 0.", call. = FALSE)
  }

  if (micro_mean <= 0) {
    base::stop("`micro_mean` must be > 0.", call. = FALSE)
  }

  if (micro_slope < 0) {
    base::stop("`micro_slope` must be >= 0.", call. = FALSE)
  }

  if (micro_lambda_min <= 0 || micro_lambda_max <= 0) {
    base::stop("Microbial intensity bounds must be > 0.", call. = FALSE)
  }

  if (micro_lambda_max <= micro_lambda_min) {
    base::stop("`micro_lambda_max` must be greater than `micro_lambda_min`.",
               call. = FALSE)
  }

  if (metat_noise < 0) {
    base::stop("`metat_noise` must be >= 0.", call. = FALSE)
  }

  if (!base::is.null(depth_labels)) {
    if (!base::is.character(depth_labels) ||
        base::length(depth_labels) != n_depth ||
        base::any(!base::nzchar(depth_labels)) ||
        base::anyDuplicated(depth_labels)) {
      base::stop(
        "`depth_labels` must be NULL or a unique non-empty character vector of length `n_depth`.",
        call. = FALSE
      )
    }
  }

  depth_levels <- if (base::is.null(depth_labels)) {
    base::paste0("D", base::seq_len(n_depth))
  } else {
    depth_labels
  }

  id <- base::expand.grid(
    plot = base::paste0("P", base::seq_len(n_plot)),
    depth = depth_levels,
    plant_id = base::paste0("Plant", base::seq_len(n_plant)),
    time = base::seq_len(n_time),
    KEEP.OUT.ATTRS = FALSE,
    stringsAsFactors = FALSE
  )

  n <- base::nrow(id)

  plot_eff <- base::as.integer(base::factor(id$plot))
  depth_idx <- base::as.integer(base::factor(id$depth, levels = depth_levels))
  depth_num <- (depth_idx - 1) / base::max(n_depth - 1, 1)

  tmax <- base::max(id$time)
  t0 <- if (base::is.null(disturbance_center)) {
    stats::median(id$time)
  } else {
    base::as.numeric(disturbance_center)
  }

  if (!base::is.finite(t0)) {
    t0 <- stats::median(id$time)
  }

  sigma2 <- (disturbance_width * tmax)^2

  if (!base::is.finite(sigma2) || sigma2 <= 0) {
    sigma2 <- (0.10 * tmax)^2
  }

  plot_random <- stats::rnorm(n_plot, 0, 0.06)[plot_eff]

  latent_base <- 0.72 -
    0.22 * depth_num +
    plot_random

  seasonal <- seasonal_amp *
    base::sin(2 * base::pi * id$time / tmax + seasonal_phase)

  disturbance <- disturbance_strength *
    base::exp(-((id$time - t0)^2) / (2 * sigma2))

  latent_truth <- latent_base +
    seasonal -
    disturbance +
    stats::rnorm(n, 0, 0.05)

  latent_truth <- clamp01(latent_truth)
  reduced_state <- 1 - latent_truth

  water_content <- clamp01(
    0.30 +
      0.38 * disturbance +
      0.20 * depth_num -
      0.10 * seasonal +
      stats::rnorm(n, 0, 0.05)
  )

  air_filled_porosity <- clamp01(
    1 - water_content +
      stats::rnorm(n, 0, 0.03)
  )

  pore_connectivity <- clamp01(
    0.65 * air_filled_porosity +
      0.25 * (1 - depth_num) +
      0.10 * latent_truth +
      stats::rnorm(n, 0, 0.05)
  )

  aqueous_connectivity <- clamp01(
    0.70 * water_content +
      0.15 * depth_num +
      stats::rnorm(n, 0, 0.05)
  )

  oxygen_availability <- clamp01(
    0.75 * air_filled_porosity +
      0.25 * latent_truth -
      0.20 * reduced_state +
      stats::rnorm(n, 0, 0.05)
  )

  DOC <- base::pmax(
    0,
    12 +
      25 * water_content +
      15 * disturbance +
      10 * reduced_state +
      stats::rnorm(n, 0, 4)
  )

  DOC_scaled <- safe_scale01(DOC)

  dissolved_organic_matter_redox <- clamp01(
    0.25 +
      0.35 * reduced_state +
      0.25 * water_content +
      stats::rnorm(n, 0, 0.07)
  )

  EAC <- base::pmax(
    0,
    35 +
      35 * latent_truth +
      15 * pore_connectivity -
      10 * reduced_state +
      stats::rnorm(n, 0, 5)
  )

  EDC <- base::pmax(
    0,
    25 +
      38 * reduced_state +
      12 * DOC_scaled +
      stats::rnorm(n, 0, 5)
  )

  redox_buffer_capacity <- base::pmax(
    0,
    EAC + EDC + stats::rnorm(n, 0, 4)
  )

  Eh <- 650 * latent_truth -
    120 * water_content +
    45 * pore_connectivity +
    stats::rnorm(n, 0, 35)

  pH <- 6.6 -
    0.75 * reduced_state +
    0.15 * DOC_scaled +
    stats::rnorm(n, 0, 0.2)

  Fe2_Fe3 <- stats::plogis(
    -4.2 * latent_truth +
      1.1 * water_content +
      0.4 * reduced_state +
      stats::rnorm(n, 0, 0.6)
  )

  Mn2_Mn4 <- stats::plogis(
    -3.5 * latent_truth +
      0.8 * water_content +
      stats::rnorm(n, 0, 0.6)
  )

  NH4_NO3 <- stats::plogis(
    -2.8 * latent_truth +
      0.7 * reduced_state +
      stats::rnorm(n, 0, 0.5)
  )

  sulfide_risk <- stats::plogis(
    2.2 * reduced_state +
      0.8 * water_content -
      1.2 * oxygen_availability +
      stats::rnorm(n, 0, 0.6)
  )

  methane_potential <- stats::plogis(
    2.6 * reduced_state +
      0.9 * DOC_scaled -
      1.4 * oxygen_availability +
      stats::rnorm(n, 0, 0.6)
  )

  nitrate_reduction_potential <- stats::plogis(
    1.8 * reduced_state +
      0.7 * DOC_scaled -
      0.5 * sulfide_risk +
      stats::rnorm(n, 0, 0.6)
  )

  dropout_prob <- base::ifelse(
    latent_truth < Eh_dropout_threshold,
    MNAR_strength * (Eh_dropout_threshold - latent_truth) /
      base::max(Eh_dropout_threshold, 1e-8),
    0
  )

  dropout_prob <- clamp01(dropout_prob)
  Eh[stats::runif(n) < dropout_prob] <- NA_real_

  Eh_stability <- base::data.frame(
    Eh = Eh,
    pH = pH,
    water_content = water_content,
    air_filled_porosity = air_filled_porosity,
    pore_connectivity = pore_connectivity,
    aqueous_connectivity = aqueous_connectivity,
    oxygen_availability = oxygen_availability,
    DOC = DOC,
    dissolved_organic_matter_redox = dissolved_organic_matter_redox,
    EAC = EAC,
    EDC = EDC,
    redox_buffer_capacity = redox_buffer_capacity,
    Fe2.Fe3 = Fe2_Fe3,
    Mn2.Mn4 = Mn2_Mn4,
    NH4.NO3 = NH4_NO3,
    sulfide_risk = sulfide_risk,
    methane_potential = methane_potential,
    nitrate_reduction_potential = nitrate_reduction_potential
  )

  hypoxia_signal <- reduced_state

  internal_regulation <- decoupling *
    stats::rnorm(n, 0, 0.10)

  ROS_load <- hypoxia_signal^2 +
    0.25 * (1 - oxygen_availability) +
    internal_regulation +
    stats::rnorm(n, 0, 0.05)

  ROS_load <- base::pmax(0, ROS_load)

  aerenchyma <- clamp01(
    0.20 +
      0.65 * hypoxia_signal +
      0.10 * water_content +
      stats::rnorm(n, 0, 0.08)
  )

  ROL_barrier <- clamp01(
    0.15 +
      0.50 * hypoxia_signal +
      0.20 * depth_num +
      0.10 * water_content +
      stats::rnorm(n, 0, 0.08)
  )

  ROL <- clamp01(
    0.20 +
      0.45 * aerenchyma -
      0.30 * ROL_barrier +
      0.20 * hypoxia_signal +
      0.12 * oxygen_availability +
      stats::rnorm(n, 0, 0.07)
  )

  root_exudates <- clamp01(
    0.25 +
      0.45 * hypoxia_signal +
      0.20 * ROS_load +
      0.12 * water_content +
      stats::rnorm(n, 0, 0.08)
  )

  organic_acids <- clamp01(
    0.20 +
      0.50 * root_exudates +
      0.20 * hypoxia_signal +
      stats::rnorm(n, 0, 0.08)
  )

  phenolics <- clamp01(
    0.18 +
      0.38 * root_exudates +
      0.25 * ROS_load +
      stats::rnorm(n, 0, 0.08)
  )

  exudate_redox_activity <- clamp01(
    0.25 +
      0.35 * organic_acids +
      0.35 * phenolics +
      0.15 * hypoxia_signal +
      stats::rnorm(n, 0, 0.06)
  )

  root_oxidative_stress <- clamp01(
    0.20 +
      0.55 * ROS_load +
      0.15 * (1 - oxygen_availability) +
      stats::rnorm(n, 0, 0.07)
  )

  root_redox_buffering <- clamp01(
    0.65 -
      0.45 * root_oxidative_stress +
      0.15 * aerenchyma +
      stats::rnorm(n, 0, 0.06)
  )

  Fe_plaque_proxy <- clamp01(
    0.15 +
      0.45 * ROL +
      0.25 * Fe2_Fe3 +
      0.10 * oxygen_availability +
      stats::rnorm(n, 0, 0.07)
  )

  ROS_flux <- base::data.frame(
    SPAD = 40 - 8 * ROS_load + stats::rnorm(n, 0, 2),
    FvFm = 0.83 - 0.35 * ROS_load + stats::rnorm(n, 0, 0.02),
    PhiPSII = 0.45 - 0.40 * ROS_load + stats::rnorm(n, 0, 0.03),
    NPQ = 0.8 + 2.0 * ROS_load + stats::rnorm(n, 0, 0.2),
    ROL = ROL,
    root_exudates = root_exudates,
    organic_acids = organic_acids,
    phenolics = phenolics,
    exudate_redox_activity = exudate_redox_activity,
    aerenchyma = aerenchyma,
    ROL_barrier = ROL_barrier,
    root_oxidative_stress = root_oxidative_stress,
    root_redox_buffering = root_redox_buffering,
    Fe_plaque_proxy = Fe_plaque_proxy
  )

  log_lambda <- base::log(micro_mean) +
    micro_slope * reduced_state +
    0.35 * root_exudates +
    0.20 * DOC_scaled -
    0.20 * oxygen_availability

  log_lambda <- base::pmin(
    base::pmax(log_lambda, base::log(micro_lambda_min)),
    base::log(micro_lambda_max)
  )

  lambda_det <- base::exp(log_lambda)

  if (base::isTRUE(stochastic_reassembly)) {
    lambda_rand <- base::rep(micro_mean, n)
    lambda_mix <- (1 - decoupling) * lambda_det +
      decoupling * lambda_rand
  } else {
    lambda_mix <- lambda_det
  }

  lambda_mix <- base::pmin(
    base::pmax(lambda_mix, micro_lambda_min),
    micro_lambda_max
  )

  if (base::any(!base::is.finite(lambda_mix))) {
    base::stop(
      "Internal error: microbial intensity became non-finite.",
      call. = FALSE
    )
  }

  micro_mat <- base::matrix(
    stats::rpois(
      n * p_micro,
      lambda = base::rep(lambda_mix, times = p_micro)
    ),
    nrow = n,
    ncol = p_micro,
    byrow = FALSE
  )

  if (zero_inflation > 0) {
    zero_mask <- base::matrix(
      stats::runif(n * p_micro) < zero_inflation,
      nrow = n,
      ncol = p_micro
    )
    micro_mat[zero_mask] <- 0L
  }

  micro_data <- base::as.data.frame(micro_mat)
  base::colnames(micro_data) <- base::paste0("ASV", base::seq_len(p_micro))

  scaled_lambda <- safe_scale01(base::log1p(lambda_mix))

  aerobic_respiration <- clamp01(
    0.20 +
      0.60 * oxygen_availability +
      0.15 * DOC_scaled +
      stats::rnorm(n, 0, 0.07)
  )

  denitrification <- clamp01(
    0.15 +
      0.55 * nitrate_reduction_potential +
      0.25 * DOC_scaled -
      0.20 * oxygen_availability +
      stats::rnorm(n, 0, 0.07)
  )

  Fe_Mn_reduction <- clamp01(
    0.15 +
      0.45 * reduced_state +
      0.25 * Fe2_Fe3 +
      0.20 * dissolved_organic_matter_redox +
      stats::rnorm(n, 0, 0.07)
  )

  EET_potential <- clamp01(
    0.15 +
      0.35 * Fe_Mn_reduction +
      0.25 * dissolved_organic_matter_redox +
      0.20 * aqueous_connectivity +
      stats::rnorm(n, 0, 0.07)
  )

  sulfate_reduction <- clamp01(
    0.10 +
      0.45 * reduced_state +
      0.25 * sulfide_risk +
      0.15 * DOC_scaled -
      0.20 * oxygen_availability +
      stats::rnorm(n, 0, 0.07)
  )

  methanogenesis <- clamp01(
    0.10 +
      0.60 * methane_potential +
      0.20 * DOC_scaled -
      0.25 * oxygen_availability -
      0.15 * sulfate_reduction +
      stats::rnorm(n, 0, 0.07)
  )

  flavin_mediator <- clamp01(
    0.15 +
      0.35 * EET_potential +
      0.25 * root_exudates +
      stats::rnorm(n, 0, 0.07)
  )

  phenazine_mediator <- clamp01(
    0.10 +
      0.30 * EET_potential +
      0.30 * root_exudates +
      0.20 * root_oxidative_stress +
      stats::rnorm(n, 0, 0.07)
  )

  quinone_humic_shuttle <- clamp01(
    0.20 +
      0.40 * dissolved_organic_matter_redox +
      0.25 * DOC_scaled +
      stats::rnorm(n, 0, 0.07)
  )

  microbial_ROS_detox <- clamp01(
    0.20 +
      0.45 * root_oxidative_stress +
      0.25 * oxygen_availability +
      stats::rnorm(n, 0, 0.07)
  )

  AMF_connectivity <- clamp01(
    0.25 +
      0.35 * root_exudates +
      0.25 * pore_connectivity -
      0.20 * water_content +
      stats::rnorm(n, 0, 0.08)
  )

  protist_grazing <- clamp01(
    0.15 +
      0.35 * aqueous_connectivity +
      0.25 * scaled_lambda +
      stats::rnorm(n, 0, 0.08)
  )

  viral_lysis <- clamp01(
    0.10 +
      0.35 * scaled_lambda +
      0.25 * root_oxidative_stress +
      0.15 * water_content +
      stats::rnorm(n, 0, 0.08)
  )

  microbial_memory <- clamp01(
    0.20 +
      0.30 * decoupling +
      0.25 * reduced_state +
      0.20 * viral_lysis +
      0.15 * protist_grazing +
      stats::rnorm(n, 0, 0.07)
  )

  microbial_redox_flexibility <- clamp01(
    0.20 +
      0.20 * aerobic_respiration +
      0.20 * denitrification +
      0.20 * EET_potential +
      0.15 * sulfate_reduction +
      0.15 * methanogenesis +
      stats::rnorm(n, 0, 0.05)
  )

  micro_traits <- base::data.frame(
    aerobic_respiration = aerobic_respiration,
    denitrification = denitrification,
    Fe_Mn_reduction = Fe_Mn_reduction,
    EET_potential = EET_potential,
    sulfate_reduction = sulfate_reduction,
    methanogenesis = methanogenesis,
    flavin_mediator = flavin_mediator,
    phenazine_mediator = phenazine_mediator,
    quinone_humic_shuttle = quinone_humic_shuttle,
    microbial_ROS_detox = microbial_ROS_detox,
    AMF_connectivity = AMF_connectivity,
    protist_grazing = protist_grazing,
    viral_lysis = viral_lysis,
    microbial_memory = microbial_memory,
    microbial_redox_flexibility = microbial_redox_flexibility
  )

  gene_drivers <- base::data.frame(
    coxA = aerobic_respiration,
    coxB = aerobic_respiration,
    cyoA = aerobic_respiration,
    cyoB = aerobic_respiration,
    sodA = microbial_ROS_detox,
    katG = microbial_ROS_detox,
    narG = denitrification,
    narH = denitrification,
    napA = denitrification,
    nirK = denitrification,
    nirS = denitrification,
    norB = denitrification,
    nosZ = denitrification,
    mtrA = EET_potential,
    mtrB = EET_potential,
    mtrC = EET_potential,
    omcA = EET_potential,
    omcS = EET_potential,
    omcZ = EET_potential,
    cymA = EET_potential,
    dsrA = sulfate_reduction,
    dsrB = sulfate_reduction,
    aprA = sulfate_reduction,
    aprB = sulfate_reduction,
    sat = sulfate_reduction,
    hdrA = sulfate_reduction,
    mcrA = methanogenesis,
    mcrB = methanogenesis,
    mcrG = methanogenesis,
    NiFe_hydrogenase = methanogenesis,
    flavin_biosynthesis = flavin_mediator,
    phenazine_biosynthesis = phenazine_mediator,
    quinone_reductase = quinone_humic_shuttle,
    fungal_sod1 = AMF_connectivity,
    fungal_CAT = AMF_connectivity,
    viral_capsid_proxy = viral_lysis
  )

  if (p_gene > base::ncol(gene_drivers)) {
    extra_n <- p_gene - base::ncol(gene_drivers)
    extra_gene <- base::replicate(
      extra_n,
      clamp01(
        0.25 * microbial_redox_flexibility +
          0.25 * microbial_memory +
          0.25 * scaled_lambda +
          stats::rnorm(n, 0, 0.10)
      )
    )
    extra_gene <- base::as.data.frame(extra_gene)
    base::names(extra_gene) <- base::paste0(
      "redox_gene_",
      base::seq_len(extra_n)
    )
    gene_drivers <- base::cbind(gene_drivers, extra_gene)
  }

  gene_drivers <- gene_drivers[, base::seq_len(p_gene), drop = FALSE]

  gene_abundance <- NULL
  gene_expression <- NULL
  gene_log2fc <- NULL

  if (gene_mode %in% c("both", "abundance")) {
    gene_abundance <- base::as.data.frame(
      base::lapply(gene_drivers, function(driver) {
        lambda_gene <- base::pmax(
          micro_lambda_min,
          micro_mean * (0.5 + 4 * driver) * (0.5 + scaled_lambda)
        )
        stats::rpois(n, lambda = lambda_gene)
      })
    )
    base::names(gene_abundance) <- base::paste0(
      base::names(gene_drivers),
      "_cov"
    )
  }

  if (gene_mode %in% c("both", "metat")) {
    gene_expression <- base::as.data.frame(
      base::lapply(gene_drivers, function(driver) {
        expr <- base::log1p(100 * driver) +
          stats::rnorm(n, 0, metat_noise)
        base::pmax(0, expr)
      })
    )
    base::names(gene_expression) <- base::paste0(
      base::names(gene_drivers),
      "_MetaT"
    )

    baseline_idx <- id$time < t0

    gene_log2fc <- base::as.data.frame(
      base::lapply(gene_expression, function(expr) {
        baseline_mean <- base::mean(expr[baseline_idx], na.rm = TRUE)
        base::log2((expr + 1e-6) / (baseline_mean + 1e-6))
      })
    )
    base::names(gene_log2fc) <- base::paste0(
      base::names(gene_drivers),
      "_log2FC"
    )
  }

  graph <- NULL

  if (base::isTRUE(include_graph) &&
      base::requireNamespace("igraph", quietly = TRUE)) {
    if (base::isTRUE(stochastic_reassembly)) {
      graph <- igraph::sample_pa(40, m = 2)
    } else {
      graph <- igraph::sample_smallworld(1, 40, 5, 0.1)
    }

    graph <- igraph::simplify(graph)
  }

  base::list(
    id = id,
    ROS_flux = ROS_flux,
    Eh_stability = Eh_stability,
    micro_data = micro_data,
    micro_traits = micro_traits,
    gene_abundance = gene_abundance,
    gene_expression = gene_expression,
    gene_log2fc = gene_log2fc,
    latent_truth = latent_truth,
    graph = graph
  )
}
